image:
  file: .gitpod.Dockerfile
tasks:
  - init: yarn && abtnode init -f --mode debug
    command: export ABT_NODE_HTTP_PORT=8080 && export ABT_NODE_HTTPS_PORT=4430 && abtnode start && abtnode dev
ports:
  - port: 8080